### ISSUE TITLE
Do you/we really care about Python 2 support?

### ISSUE THREAD

**Issue by njsmith** [jeamland/wsproto#10]
The reason I ask is that I think `frame_protocol.py` has some issues with accidentally-quadratic complexity and excessive buffering of partial messages, but in trying to sort them out came to the conclusion that it would be much more readable/maintainable if the state machine were rewritten to use `yield from`-based generators. (The idea is that you parse as much as you can, yield when you need more data, and then keep parsing when resumed -- it turns the state machine into straight-line code.) But that's a Python 3.3+ feature...

Personally I'm interested in wsproto because I want to use it in an async HTTP server, so I don't care about Python 2 myself :-)

otoh I noticed there's currently a rather blatant bug on py2, which is that you can't send TEXT messages because it only checks for `str`, not `unicode`.

**Comment by njsmith** [comment]
[Here's what I mean about using `yield from`](https://github.com/jeamland/wsproto/blob/dc8f661309079637295f60e3a19b204273a9b49c/wsproto/frame_protocol.py#L115-L303).

```
 wsproto/frame_protocol.py | 483 ++++++++++++++++++++--------------------------
 1 file changed, 214 insertions(+), 269 deletions(-)
```

**Comment by merrellb** [comment]
+1 on dropping Python 2 support (and frankly wouldn't mind jumping all the way 3.5 and 'await' :-)

@njsmith I've managed to get wsproto working fairly well with trio (really digging it).  Surprised how easy it was (especially I am quite new to async).

**Comment by jeamland** [comment]
Python 2 support dropped.
